### ISSUE TITLE
mac os not working on node  13 

### ISSUE THREAD

**Issue by ivosanchez** [BuiltonDev/builton-demo-store#72]
I can make it install on a mac using node 12 not 13

**Comment by ivosanchez** [comment]
after install, it warns that React Hook useEffect has missing dependencies, 
namely, bag, filterOptions, fetchProducts 
Isnt there anywhere some instructions on how to use this shop with one's products once these have been uploaded to the dashboard??

 (incidentally, the python shopify-formatted products import script works very well)

**Comment by tigo0** [comment]
Hey @ivosanchez,
thanks for the report. 
Apparently node-sass was breaking on node 13. A fix has been pushed and released. After you pull the fix, if it still doesn't work, please try to run `npm rebuild node-sass`.
