### ISSUE TITLE
 React Hook useEffect has missing dependencies

### ISSUE THREAD

**Issue by ivosanchez** [BuiltonDev/builton-demo-store#73]
At runtime, it warns that React Hook useEffect has missing dependencies,
namely, bag, filterOptions, fetchProducts

and it is noted  in the readme that the shop wont work with other product sets. But isn't there anywhere any instructions on how to use this shop with one's products once these have been uploaded to the dashboard?? 

(incidentally, the python shopify-formatted products import script works very well)

**Comment by tigo0** [comment]
Hey @ivosanchez,
we support Shopify imported products, so I assume thats the reason why they worked for you. ( If you need more information on this https://medium.com/builton/want-more-flexibility-than-shopify-offers-d94cc833591c)We do mention in a couple of places that the products need to be created locally (Point 6 of the requirements guide about ML, and _Note_ in installation guide) but I agree it can be made more clear. Also we we will provide data dump of products, that can be CURLed into the project, so it will work out of the box in future.

The idea of this demo is to provide you with an in-depth example on how to set up your environment and get it going with BuiltOn API's. The products in the Sneakers Demo store are specifically created to match the needs of this Demo Store (It is really hard to generalize for any use case), but it will work when we have the products dump CURLed in the db locally.

As of the dependencies. It is mostly a lint warning and a good to have improvement (more can be read https://reactjs.org/docs/hooks-rules.html). We will see how that can be improved, but it shouldn't really be a show stopper.

**Comment by ivosanchez** [comment]
maybe I should not add any suggestions, cuz I realize that my coding skills are too limited, so the demo shop is fine as it is, it's just that I'm missing a lot of background.  but I think that, a tutorial based on making a fully-working demo shop, with demo data, could help a lot. Some of us are fine with just mimicking your lead. We can't be very creative yet. :-)

**Comment by tigo0** [comment]
Thats great to hear. I will make sure that after the holidays we get some of the missing bits (products) and a guidelines on how to use them are included as well.
